#!/usr/bin/zsh

[[ -n "$GIT_USER_NAME"  ]] && export GIT_AUTHOR_NAME="$GIT_USER_NAME" GIT_COMMITTER_NAME="$GIT_USER_NAME"
[[ -n "$GIT_USER_EMAIL" ]] && export GIT_AUTHOR_EMAIL="$GIT_USER_EMAIL" GIT_COMMITTER_EMAIL="$GIT_USER_EMAIL"
